# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 70%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "node_modules/**"
  - "dist/**"
  - "coverage/**"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "vitest.config.ts"
  - ".eslintrc.cjs"

flags:
  unittests:
    paths:
      - src/
    carryforward: true
