name: Bug Report
description: 버그를 신고합니다
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        버그 신고를 위해 아래 양식을 작성해주세요.

  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 버그에 대해 명확하게 설명해주세요
      placeholder: 어떤 버그인가요?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 단계를 설명해주세요
      placeholder: |
        1. '...'로 이동
        2. '...'를 클릭
        3. '...'까지 스크롤
        4. 오류 확인
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 예상 동작
      description: 정상적으로 동작했을 때 어떻게 되어야 하나요?
      placeholder: 예상 동작을 설명해주세요
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      description: 실제로 어떻게 동작했나요?
      placeholder: 실제 동작을 설명해주세요
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      description: 버그의 심각도를 선택해주세요
      options:
        - Low (불편하지만 사용 가능)
        - Medium (기능 제한)
        - High (주요 기능 불가)
        - Critical (시스템 중단)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 환경 정보
      description: 버그가 발생한 환경을 설명해주세요
      placeholder: |
        - OS: [예: macOS 14.0]
        - Node.js: [예: 20.10.0]
        - npm: [예: 10.2.0]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 로그 / 스크린샷
      description: 관련 로그나 스크린샷을 첨부해주세요
      placeholder: 에러 로그를 붙여넣거나 스크린샷을 드래그해주세요
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: 이슈 제출 전 확인사항
      options:
        - label: 기존 이슈에서 동일한 버그를 검색했습니다
          required: true
        - label: 최신 버전에서 테스트했습니다
          required: false
