name: Feature Request
description: 새로운 기능을 제안합니다
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        새로운 기능 제안을 위해 아래 양식을 작성해주세요.

  - type: textarea
    id: problem
    attributes:
      label: 해결하려는 문제
      description: 이 기능이 해결하려는 문제나 불편함을 설명해주세요
      placeholder: "현재 ~할 때 ~한 문제가 있습니다..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 제안하는 해결책
      description: 원하는 기능이나 해결책을 설명해주세요
      placeholder: "~하는 기능이 있으면 좋겠습니다..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 고려한 대안
      description: 다른 해결 방법을 고려해 보셨나요?
      placeholder: "~하는 방법도 있지만..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 기능의 중요도를 선택해주세요
      options:
        - Nice to have (있으면 좋음)
        - Should have (필요함)
        - Must have (필수)
    validations:
      required: true

  - type: dropdown
    id: approval-level
    attributes:
      label: 예상 승인 레벨
      description: AI Orchestrator 승인 레벨 (불확실하면 L2 선택)
      options:
        - L1 - 일반 코드 변경
        - L2 - 아키텍처 변경
        - L3 - 보안 관련
        - L4 - 프로덕션 배포
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 참고 자료, 스크린샷, 예시 등을 첨부해주세요
      placeholder: 추가 정보를 입력해주세요
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      description: 이슈 제출 전 확인사항
      options:
        - label: 기존 이슈에서 동일한 요청을 검색했습니다
          required: true
        - label: 이 기능이 프로젝트 범위에 적합하다고 생각합니다
          required: false
